name: mpibrasil
description: Uma aplicação para auxilizar profissionais de saúde na prescrição de medicamentos para idosos.
# https://stackoverflow.com/questions/55330105/how-to-increment-build-number-of-flutter-ios-app-when-deploying-with-codemagic
version: 1.0.0+92


environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^5.0.0
  shared_preferences: ^0.5.7+2
  cupertino_icons: ^0.1.2
  flutter_icons: ^1.1.0 # https://oblador.github.io/react-native-vector-icons/
  url_launcher: ^5.4.2
  share: ^0.6.3+6
  
  flutter_speed_dial: ^1.2.5 # Floating button menu
  grouped_buttons: ^1.0.4    # Radiobox 
  flutter_mailer: ^0.4.1+1   # Enviar email pelo app padrão
  mask_text_input_formatter: ^1.0.7
  
  diacritic: ^0.1.1 # simplifica palavras com acentos e caracteres especiais
  intl: ^0.15.8
  http: 0.12.0+4
  json_annotation: ^3.0.1
  markdown_widget: ^1.2.0
  introduction_screen: ^1.0.7
  package_info_plus: ^0.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_launcher_name: "^0.0.1"
  flutter_test:
    sdk: flutter
  
  # flutter pub run build_runner build  --delete-conflicting-outputs
  build_runner: ^1.8.1 # automatically generate json classes
  json_serializable: ^3.3.0


# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true 
  image_path_ios: "assets/images/app_icon_ios.png"
  image_path_android: "assets/images/app_icon_android.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_android.png"

# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "MPI Brasil"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/partners/pmosocial/
    - assets/images/partners/ufba/
    - assets/images/partners/uesb/
    - assets/undraw/
   
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700 
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
