name: mpibrasil
description: Uma aplicação para auxilizar profissionais de saúde na prescrição de medicamentos para idosos.
version: 2.3.3+0
publish_to: 'none'

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # app icons
  cupertino_icons: ^1.0.9
  material_symbols_icons: ^4.2928.1

  # packages
  diacritic: ^0.1.6
  flutter_mailer: ^3.0.1
  flutter_secure_storage: ^10.2.0
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.3.0
  http: ^1.6.0
  intl: ^0.20.2
  intl_utils: ^2.8.11
  introduction_screen: ^4.0.0
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+8
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^10.1.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  share_plus: ^13.1.0
  url_launcher: ^6.3.2
  flutter_linkify: ^6.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

  # dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.5
  flutter_launcher_icons: ^0.14.4
  json_serializable: ^6.9.5

# dart run flutter_launcher_icons:main
flutter_launcher_icons:
  ios: true
  android: true
  image_path: "assets/images/app_icon_ios.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_ios.png"

# dart run intl_utils:generate
flutter_intl:
  enabled: true
  main_locale: pt
  arb_dir: lib/l10n

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/images/
    - assets/images/partners/socialtech/
    - assets/images/partners/pmosocial/
    - assets/images/partners/ufba/
    - assets/images/partners/uesb/
    - assets/undraw/
    - assets/undraw_svg/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
