name: mpibrasil
description: Uma aplicação para auxilizar profissionais de saúde na prescrição de medicamentos para idosos.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+91

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^3.2.0
  shared_preferences: ^0.5.7+2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_icons: ^1.1.0 # https://oblador.github.io/react-native-vector-icons/
  url_launcher: ^5.4.2
  share: ^0.6.3+6
  
  flutter_speed_dial: ^1.2.5 # Floating button menu
  grouped_buttons: ^1.0.4    # Radiobox 
  flutter_mailer: ^0.4.1+1   # Enviar email pelo app padrão

  diacritic: ^0.1.1 # simplifica palavras com acentos e caracteres especiais
  intl: ^0.15.8
  http: 0.12.0+4
  json_annotation: ^3.0.1
  markdown_widget: ^1.1.9

dev_dependencies:
  flutter_launcher_icons: ^0.7.4
  flutter_launcher_name: "^0.0.1"
  # flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter
  # flutter pub run build_runner build  --delete-conflicting-outputs
  build_runner: ^1.8.1 # automatically generate json classes
  json_serializable: ^3.3.0




# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/images/logo.png"

# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "MPI Brasil"

#flutter pub pub run flutter_native_splash:create
# flutter_native_splash:
#   image: assets/images/logo-green.png
#   color: "42a5f5"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/
   - assets/images/partners/pmosocial/
   - assets/images/partners/ufba/
   - assets/images/partners/uesb/
   - assets/images/
   
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700 
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
          

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
