name: mpibrasil
description: Uma aplicação para auxilizar profissionais de saúde na prescrição de medicamentos para idosos.
version: 2.1.0+0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # app icons
  cupertino_icons: ^1.0.8
  material_symbols_icons: ^4.2785.1

  # packages
  diacritic: ^0.1.5
  flutter_mailer: ^2.1.2
  flutter_secure_storage: ^4.2.1
  flutter_speed_dial: ^7.0.0
  flutter_svg: ^2.0.10+1
  http: ^1.2.2
  intl: ^0.19.0
  intl_utils: ^2.8.7
  introduction_screen: ^3.1.14
  json_annotation: ^4.9.0
  markdown_widget: ^2.3.2+6
  mask_text_input_formatter: ^2.9.0
  package_info_plus: ^8.0.2
  provider: ^6.1.2
  share_plus: ^10.0.2
  url_launcher: ^6.3.0
  flutter_linkify: ^6.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

  # dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.12
  flutter_launcher_icons: ^0.14.1
  json_serializable: ^6.8.0

# dart run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/images/app_icon_ios.png"
  image_path_android: "assets/images/app_icon_android.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon_android.png"

# dart run intl_utils:generate
flutter_intl:
  enabled: true
  main_locale: pt
  arb_dir: lib/l10n

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/docs/
    - assets/images/
    - assets/images/partners/socialtech/
    - assets/images/partners/pmosocial/
    - assets/images/partners/ufba/
    - assets/images/partners/uesb/
    - assets/undraw/
    - assets/undraw_svg/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito-Regular.ttf
